cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/sghose/GCI/pysoy/.waf3-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Tools/c_config.py", line 460, in run_c_code\n    bld.compile()\n  File "/home/sghose/GCI/pysoy/.waf3-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Build.py", line 198, in compile\n    raise Errors.BuildError(self.producer.error)\nwaflib.Errors.BuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 3065518188: cprogram test.c.1.o -> testprog}\n[\'/usr/bin/gcc\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\', \'test.c.1.o\', \'-o\', \'/home/sghose/GCI/pysoy/build/.conf_check_2c88286400682194d779e7e08304c1d2/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib\', \'-lpython3.3\']\n'
